site_name: snorql

# Material theme
theme:
  name: 'material'
  favicon: 🪀
  social:
    - type: 'github'
      link: 'https://github.com/udaan-com/snorql'

nav:
  - Home: index.md
  - About the project: sections/about.md
  - Getting Started: sections/getting-started.md
  - Usage:
      - How to integrate snorql in your project: sections/integrate-snorql-to-project.md
      - Enable snorql-extensions in your project: sections/enable-snorql-extensions.md
      - Build your own custom metrics using snorql: sections/build-custom-metrics.md
        - Example to create your first custom metric: ../snorql-extensions/README.md
  - Kotlin Documentation: sections/kotlin-doc-for-website.md
  - Roadmap: sections/roadmap.md
  - Contributing: ../CONTRIBUTING.md
  - License: sections/license-details.md
  - Contact: sections/contact.md
  - Acknowledgments: sections/acknowledgements.md

extra_css:
  - colors.css
