name: Advanced Usage

on: push

jobs:
  genrate-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run script file
        run: |
          chmod +x script.sh
          script.sh
        shell: bash