name: Readme

on: push

jobs:
  generate-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run script file
        run: |
          chmod +x ./doc/populate-readme.sh
          ./doc/populate-readme.sh
        shell: bash
      - name: Current branch name
        run: echo running on branch ${GITHUB_REF##*/}
      - uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${GITHUB_REF##*/}