name: Simple Usage

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Finding files and store to output
        id: finding-files
        run: |
          echo "::set-output name=files::$(find . -name '*.md' -print)"
        working-directory: pandoc
      - uses: docker://pandoc/core:2.16.2
        with:
          args: "--output=example.md pandoc/one.md pandoc/two.md"