name: reviewdog
on: [pull_request]

jobs:
  detekt:
    name: Check Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: ${{ github.head_ref }}

      - name: detekt
        uses: lakshmi-udaan/replicate-udaan-linters@v0.4.test
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reviewdog_level: error
          reviewdog_filter: added
          reviewdog_reporter: github-check
          detekt_config: default-detekt-config.yml
          detekt_excludes: "**/build/**,**/.idea/**"
          fail_on_error: false

